var num1=4;
console.log("the first number"+num1);
var num2=3.5;
console.log("the second number"+num2);
var num3=-10;
console.log("the third number"+num3);
var num4=0;
console.log("the fourth number"+num4);
var string1="Bob";
console.log("the first string"+string1);
var string2="Sticky";
console.log("the second string"+string2);
var string3="Butt";
console.log("the third string"+string3);
var boolean1=true;
console.log("boolean true"+boolean1);
var boolean2=false;
console.log("boolean false"+boolean2);
var booger="";
console.log("undefined variable" + booger);
